// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/client/historical_data"
	"github.com/nii236/fxcm-go/client/market_data"
	"github.com/nii236/fxcm-go/client/trading_orders"
	"github.com/nii236/fxcm-go/client/trading_tables"
)

// Default fxcm HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.fxcm.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new fxcm HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Fxcm {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new fxcm HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Fxcm {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new fxcm client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Fxcm {
	cli := new(Fxcm)
	cli.Transport = transport

	cli.HistoricalData = historical_data.New(transport, formats)

	cli.MarketData = market_data.New(transport, formats)

	cli.TradingOrders = trading_orders.New(transport, formats)

	cli.TradingTables = trading_tables.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Fxcm is a client for fxcm
type Fxcm struct {
	HistoricalData *historical_data.Client

	MarketData *market_data.Client

	TradingOrders *trading_orders.Client

	TradingTables *trading_tables.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Fxcm) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.HistoricalData.SetTransport(transport)

	c.MarketData.SetTransport(transport)

	c.TradingOrders.SetTransport(transport)

	c.TradingTables.SetTransport(transport)

}
