// Code generated by go-swagger; DO NOT EDIT.

package trading_orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/models"
)

// NewDeleteOrderParams creates a new DeleteOrderParams object
// with the default values initialized.
func NewDeleteOrderParams() *DeleteOrderParams {
	var ()
	return &DeleteOrderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrderParamsWithTimeout creates a new DeleteOrderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOrderParamsWithTimeout(timeout time.Duration) *DeleteOrderParams {
	var ()
	return &DeleteOrderParams{

		timeout: timeout,
	}
}

// NewDeleteOrderParamsWithContext creates a new DeleteOrderParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOrderParamsWithContext(ctx context.Context) *DeleteOrderParams {
	var ()
	return &DeleteOrderParams{

		Context: ctx,
	}
}

// NewDeleteOrderParamsWithHTTPClient creates a new DeleteOrderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOrderParamsWithHTTPClient(client *http.Client) *DeleteOrderParams {
	var ()
	return &DeleteOrderParams{
		HTTPClient: client,
	}
}

/*DeleteOrderParams contains all the parameters to send to the API endpoint
for the delete order operation typically these are written to a http.Request
*/
type DeleteOrderParams struct {

	/*Body*/
	Body models.DeleteOrderRequestDefinition
	/*OrderID
	  The order identifier.

	*/
	OrderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete order params
func (o *DeleteOrderParams) WithTimeout(timeout time.Duration) *DeleteOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete order params
func (o *DeleteOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete order params
func (o *DeleteOrderParams) WithContext(ctx context.Context) *DeleteOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete order params
func (o *DeleteOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete order params
func (o *DeleteOrderParams) WithHTTPClient(client *http.Client) *DeleteOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete order params
func (o *DeleteOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete order params
func (o *DeleteOrderParams) WithBody(body models.DeleteOrderRequestDefinition) *DeleteOrderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete order params
func (o *DeleteOrderParams) SetBody(body models.DeleteOrderRequestDefinition) {
	o.Body = body
}

// WithOrderID adds the orderID to the delete order params
func (o *DeleteOrderParams) WithOrderID(orderID string) *DeleteOrderParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the delete order params
func (o *DeleteOrderParams) SetOrderID(orderID string) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param order_id
	qrOrderID := o.OrderID
	qOrderID := qrOrderID
	if qOrderID != "" {
		if err := r.SetQueryParam("order_id", qOrderID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
