// Code generated by go-swagger; DO NOT EDIT.

package trading_orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOpenTradeParams creates a new OpenTradeParams object
// with the default values initialized.
func NewOpenTradeParams() *OpenTradeParams {
	var ()
	return &OpenTradeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOpenTradeParamsWithTimeout creates a new OpenTradeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOpenTradeParamsWithTimeout(timeout time.Duration) *OpenTradeParams {
	var ()
	return &OpenTradeParams{

		timeout: timeout,
	}
}

// NewOpenTradeParamsWithContext creates a new OpenTradeParams object
// with the default values initialized, and the ability to set a context for a request
func NewOpenTradeParamsWithContext(ctx context.Context) *OpenTradeParams {
	var ()
	return &OpenTradeParams{

		Context: ctx,
	}
}

// NewOpenTradeParamsWithHTTPClient creates a new OpenTradeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOpenTradeParamsWithHTTPClient(client *http.Client) *OpenTradeParams {
	var ()
	return &OpenTradeParams{
		HTTPClient: client,
	}
}

/*OpenTradeParams contains all the parameters to send to the API endpoint
for the open trade operation typically these are written to a http.Request
*/
type OpenTradeParams struct {

	/*AccountID
	  The trade‘s account identifier

	*/
	AccountID string
	/*Amount
	  The trade‘s amount in lots.

	*/
	Amount string
	/*AtMarket
	  Defines the market range.

	*/
	AtMarket float64
	/*Body*/
	Body interface{}
	/*IsBuy
	  Defines the trade‘s market side (if true, then buy trade,otherwise sell trade). Temporarily not required by the server and defaults to true but this will change.

	*/
	IsBuy *bool
	/*IsInPips
	  Defines if the trade‘s stop/limit rate is in pips.

	*/
	IsInPips *bool
	/*Limit
	  The trade‘s limit rate.

	*/
	Limit *float64
	/*OrderType
	  The type of the order execution. Market Order type choices “AtMarket”, “MarketRange”.

	*/
	OrderType string
	/*Rate
	  The trade‘s rate.

	*/
	Rate *float64
	/*Stop
	  The trade‘s stop rate.

	*/
	Stop *float64
	/*Symbol
	  The trade‘s account identifier

	*/
	Symbol string
	/*TimeInForce
	  Time in force choices “IOC”, “GTC”, “FOK”, “DAY”, “GTD”.

	*/
	TimeInForce string
	/*TrailingStep
	  The trailing step for the stop rate.

	*/
	TrailingStep *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the open trade params
func (o *OpenTradeParams) WithTimeout(timeout time.Duration) *OpenTradeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the open trade params
func (o *OpenTradeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the open trade params
func (o *OpenTradeParams) WithContext(ctx context.Context) *OpenTradeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the open trade params
func (o *OpenTradeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the open trade params
func (o *OpenTradeParams) WithHTTPClient(client *http.Client) *OpenTradeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the open trade params
func (o *OpenTradeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the open trade params
func (o *OpenTradeParams) WithAccountID(accountID string) *OpenTradeParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the open trade params
func (o *OpenTradeParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithAmount adds the amount to the open trade params
func (o *OpenTradeParams) WithAmount(amount string) *OpenTradeParams {
	o.SetAmount(amount)
	return o
}

// SetAmount adds the amount to the open trade params
func (o *OpenTradeParams) SetAmount(amount string) {
	o.Amount = amount
}

// WithAtMarket adds the atMarket to the open trade params
func (o *OpenTradeParams) WithAtMarket(atMarket float64) *OpenTradeParams {
	o.SetAtMarket(atMarket)
	return o
}

// SetAtMarket adds the atMarket to the open trade params
func (o *OpenTradeParams) SetAtMarket(atMarket float64) {
	o.AtMarket = atMarket
}

// WithBody adds the body to the open trade params
func (o *OpenTradeParams) WithBody(body interface{}) *OpenTradeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the open trade params
func (o *OpenTradeParams) SetBody(body interface{}) {
	o.Body = body
}

// WithIsBuy adds the isBuy to the open trade params
func (o *OpenTradeParams) WithIsBuy(isBuy *bool) *OpenTradeParams {
	o.SetIsBuy(isBuy)
	return o
}

// SetIsBuy adds the isBuy to the open trade params
func (o *OpenTradeParams) SetIsBuy(isBuy *bool) {
	o.IsBuy = isBuy
}

// WithIsInPips adds the isInPips to the open trade params
func (o *OpenTradeParams) WithIsInPips(isInPips *bool) *OpenTradeParams {
	o.SetIsInPips(isInPips)
	return o
}

// SetIsInPips adds the isInPips to the open trade params
func (o *OpenTradeParams) SetIsInPips(isInPips *bool) {
	o.IsInPips = isInPips
}

// WithLimit adds the limit to the open trade params
func (o *OpenTradeParams) WithLimit(limit *float64) *OpenTradeParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the open trade params
func (o *OpenTradeParams) SetLimit(limit *float64) {
	o.Limit = limit
}

// WithOrderType adds the orderType to the open trade params
func (o *OpenTradeParams) WithOrderType(orderType string) *OpenTradeParams {
	o.SetOrderType(orderType)
	return o
}

// SetOrderType adds the orderType to the open trade params
func (o *OpenTradeParams) SetOrderType(orderType string) {
	o.OrderType = orderType
}

// WithRate adds the rate to the open trade params
func (o *OpenTradeParams) WithRate(rate *float64) *OpenTradeParams {
	o.SetRate(rate)
	return o
}

// SetRate adds the rate to the open trade params
func (o *OpenTradeParams) SetRate(rate *float64) {
	o.Rate = rate
}

// WithStop adds the stop to the open trade params
func (o *OpenTradeParams) WithStop(stop *float64) *OpenTradeParams {
	o.SetStop(stop)
	return o
}

// SetStop adds the stop to the open trade params
func (o *OpenTradeParams) SetStop(stop *float64) {
	o.Stop = stop
}

// WithSymbol adds the symbol to the open trade params
func (o *OpenTradeParams) WithSymbol(symbol string) *OpenTradeParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the open trade params
func (o *OpenTradeParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WithTimeInForce adds the timeInForce to the open trade params
func (o *OpenTradeParams) WithTimeInForce(timeInForce string) *OpenTradeParams {
	o.SetTimeInForce(timeInForce)
	return o
}

// SetTimeInForce adds the timeInForce to the open trade params
func (o *OpenTradeParams) SetTimeInForce(timeInForce string) {
	o.TimeInForce = timeInForce
}

// WithTrailingStep adds the trailingStep to the open trade params
func (o *OpenTradeParams) WithTrailingStep(trailingStep *float64) *OpenTradeParams {
	o.SetTrailingStep(trailingStep)
	return o
}

// SetTrailingStep adds the trailingStep to the open trade params
func (o *OpenTradeParams) SetTrailingStep(trailingStep *float64) {
	o.TrailingStep = trailingStep
}

// WriteToRequest writes these params to a swagger request
func (o *OpenTradeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param account_id
	qrAccountID := o.AccountID
	qAccountID := qrAccountID
	if qAccountID != "" {
		if err := r.SetQueryParam("account_id", qAccountID); err != nil {
			return err
		}
	}

	// query param amount
	qrAmount := o.Amount
	qAmount := qrAmount
	if qAmount != "" {
		if err := r.SetQueryParam("amount", qAmount); err != nil {
			return err
		}
	}

	// query param at_market
	qrAtMarket := o.AtMarket
	qAtMarket := swag.FormatFloat64(qrAtMarket)
	if qAtMarket != "" {
		if err := r.SetQueryParam("at_market", qAtMarket); err != nil {
			return err
		}
	}

	if o.IsBuy != nil {

		// query param is_buy
		var qrIsBuy bool
		if o.IsBuy != nil {
			qrIsBuy = *o.IsBuy
		}
		qIsBuy := swag.FormatBool(qrIsBuy)
		if qIsBuy != "" {
			if err := r.SetQueryParam("is_buy", qIsBuy); err != nil {
				return err
			}
		}

	}

	if o.IsInPips != nil {

		// query param is_in_pips
		var qrIsInPips bool
		if o.IsInPips != nil {
			qrIsInPips = *o.IsInPips
		}
		qIsInPips := swag.FormatBool(qrIsInPips)
		if qIsInPips != "" {
			if err := r.SetQueryParam("is_in_pips", qIsInPips); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit float64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatFloat64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	// query param order_type
	qrOrderType := o.OrderType
	qOrderType := qrOrderType
	if qOrderType != "" {
		if err := r.SetQueryParam("order_type", qOrderType); err != nil {
			return err
		}
	}

	if o.Rate != nil {

		// query param rate
		var qrRate float64
		if o.Rate != nil {
			qrRate = *o.Rate
		}
		qRate := swag.FormatFloat64(qrRate)
		if qRate != "" {
			if err := r.SetQueryParam("rate", qRate); err != nil {
				return err
			}
		}

	}

	if o.Stop != nil {

		// query param stop
		var qrStop float64
		if o.Stop != nil {
			qrStop = *o.Stop
		}
		qStop := swag.FormatFloat64(qrStop)
		if qStop != "" {
			if err := r.SetQueryParam("stop", qStop); err != nil {
				return err
			}
		}

	}

	// query param symbol
	qrSymbol := o.Symbol
	qSymbol := qrSymbol
	if qSymbol != "" {
		if err := r.SetQueryParam("symbol", qSymbol); err != nil {
			return err
		}
	}

	// query param time_in_force
	qrTimeInForce := o.TimeInForce
	qTimeInForce := qrTimeInForce
	if qTimeInForce != "" {
		if err := r.SetQueryParam("time_in_force", qTimeInForce); err != nil {
			return err
		}
	}

	if o.TrailingStep != nil {

		// query param trailing_step
		var qrTrailingStep float64
		if o.TrailingStep != nil {
			qrTrailingStep = *o.TrailingStep
		}
		qTrailingStep := swag.FormatFloat64(qrTrailingStep)
		if qTrailingStep != "" {
			if err := r.SetQueryParam("trailing_step", qTrailingStep); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
