// Code generated by go-swagger; DO NOT EDIT.

package market_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/models"
)

// NewMarketDataSubscribeMarketDataParams creates a new MarketDataSubscribeMarketDataParams object
// with the default values initialized.
func NewMarketDataSubscribeMarketDataParams() *MarketDataSubscribeMarketDataParams {
	var ()
	return &MarketDataSubscribeMarketDataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMarketDataSubscribeMarketDataParamsWithTimeout creates a new MarketDataSubscribeMarketDataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMarketDataSubscribeMarketDataParamsWithTimeout(timeout time.Duration) *MarketDataSubscribeMarketDataParams {
	var ()
	return &MarketDataSubscribeMarketDataParams{

		timeout: timeout,
	}
}

// NewMarketDataSubscribeMarketDataParamsWithContext creates a new MarketDataSubscribeMarketDataParams object
// with the default values initialized, and the ability to set a context for a request
func NewMarketDataSubscribeMarketDataParamsWithContext(ctx context.Context) *MarketDataSubscribeMarketDataParams {
	var ()
	return &MarketDataSubscribeMarketDataParams{

		Context: ctx,
	}
}

// NewMarketDataSubscribeMarketDataParamsWithHTTPClient creates a new MarketDataSubscribeMarketDataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMarketDataSubscribeMarketDataParamsWithHTTPClient(client *http.Client) *MarketDataSubscribeMarketDataParams {
	var ()
	return &MarketDataSubscribeMarketDataParams{
		HTTPClient: client,
	}
}

/*MarketDataSubscribeMarketDataParams contains all the parameters to send to the API endpoint
for the market data subscribe market data operation typically these are written to a http.Request
*/
type MarketDataSubscribeMarketDataParams struct {

	/*Accept
	  Acceptable response MIME type

	*/
	Accept string
	/*Authorization
	  Authorization string containing “Bearer “, ID of socke.io connection and persistent token

	*/
	Authorization string
	/*ContentType
	  Media type of the request

	*/
	ContentType string
	/*UserAgent
	  Identification of the client software

	*/
	UserAgent string
	/*Body*/
	Body *models.SubscribeMarketDataRequestDefinition

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithTimeout(timeout time.Duration) *MarketDataSubscribeMarketDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithContext(ctx context.Context) *MarketDataSubscribeMarketDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithHTTPClient(client *http.Client) *MarketDataSubscribeMarketDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithAccept(accept string) *MarketDataSubscribeMarketDataParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetAccept(accept string) {
	o.Accept = accept
}

// WithAuthorization adds the authorization to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithAuthorization(authorization string) *MarketDataSubscribeMarketDataParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithContentType adds the contentType to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithContentType(contentType string) *MarketDataSubscribeMarketDataParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithUserAgent adds the userAgent to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithUserAgent(userAgent string) *MarketDataSubscribeMarketDataParams {
	o.SetUserAgent(userAgent)
	return o
}

// SetUserAgent adds the userAgent to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetUserAgent(userAgent string) {
	o.UserAgent = userAgent
}

// WithBody adds the body to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) WithBody(body *models.SubscribeMarketDataRequestDefinition) *MarketDataSubscribeMarketDataParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the market data subscribe market data params
func (o *MarketDataSubscribeMarketDataParams) SetBody(body *models.SubscribeMarketDataRequestDefinition) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MarketDataSubscribeMarketDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Accept
	if err := r.SetHeaderParam("Accept", o.Accept); err != nil {
		return err
	}

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param User-Agent
	if err := r.SetHeaderParam("User-Agent", o.UserAgent); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
