// Code generated by go-swagger; DO NOT EDIT.

package market_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/models"
)

// MarketDataUnsubscribeMarketDataReader is a Reader for the MarketDataUnsubscribeMarketData structure.
type MarketDataUnsubscribeMarketDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MarketDataUnsubscribeMarketDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMarketDataUnsubscribeMarketDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewMarketDataUnsubscribeMarketDataUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewMarketDataUnsubscribeMarketDataForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewMarketDataUnsubscribeMarketDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMarketDataUnsubscribeMarketDataOK creates a MarketDataUnsubscribeMarketDataOK with default headers values
func NewMarketDataUnsubscribeMarketDataOK() *MarketDataUnsubscribeMarketDataOK {
	return &MarketDataUnsubscribeMarketDataOK{}
}

/*MarketDataUnsubscribeMarketDataOK handles this case with default header values.

OK
*/
type MarketDataUnsubscribeMarketDataOK struct {
	Payload *models.UnsubscribeMarketDataResponseDefinition
}

func (o *MarketDataUnsubscribeMarketDataOK) Error() string {
	return fmt.Sprintf("[POST /unsubscribe][%d] marketDataUnsubscribeMarketDataOK  %+v", 200, o.Payload)
}

func (o *MarketDataUnsubscribeMarketDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnsubscribeMarketDataResponseDefinition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMarketDataUnsubscribeMarketDataUnauthorized creates a MarketDataUnsubscribeMarketDataUnauthorized with default headers values
func NewMarketDataUnsubscribeMarketDataUnauthorized() *MarketDataUnsubscribeMarketDataUnauthorized {
	return &MarketDataUnsubscribeMarketDataUnauthorized{}
}

/*MarketDataUnsubscribeMarketDataUnauthorized handles this case with default header values.

Unauthorized
*/
type MarketDataUnsubscribeMarketDataUnauthorized struct {
	Payload *models.Error401Unauthorized
}

func (o *MarketDataUnsubscribeMarketDataUnauthorized) Error() string {
	return fmt.Sprintf("[POST /unsubscribe][%d] marketDataUnsubscribeMarketDataUnauthorized  %+v", 401, o.Payload)
}

func (o *MarketDataUnsubscribeMarketDataUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error401Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMarketDataUnsubscribeMarketDataForbidden creates a MarketDataUnsubscribeMarketDataForbidden with default headers values
func NewMarketDataUnsubscribeMarketDataForbidden() *MarketDataUnsubscribeMarketDataForbidden {
	return &MarketDataUnsubscribeMarketDataForbidden{}
}

/*MarketDataUnsubscribeMarketDataForbidden handles this case with default header values.

Forbidden
*/
type MarketDataUnsubscribeMarketDataForbidden struct {
	Payload *models.Error403Forbidden
}

func (o *MarketDataUnsubscribeMarketDataForbidden) Error() string {
	return fmt.Sprintf("[POST /unsubscribe][%d] marketDataUnsubscribeMarketDataForbidden  %+v", 403, o.Payload)
}

func (o *MarketDataUnsubscribeMarketDataForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error403Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMarketDataUnsubscribeMarketDataNotFound creates a MarketDataUnsubscribeMarketDataNotFound with default headers values
func NewMarketDataUnsubscribeMarketDataNotFound() *MarketDataUnsubscribeMarketDataNotFound {
	return &MarketDataUnsubscribeMarketDataNotFound{}
}

/*MarketDataUnsubscribeMarketDataNotFound handles this case with default header values.

Not found
*/
type MarketDataUnsubscribeMarketDataNotFound struct {
	Payload *models.Error404NotFound
}

func (o *MarketDataUnsubscribeMarketDataNotFound) Error() string {
	return fmt.Sprintf("[POST /unsubscribe][%d] marketDataUnsubscribeMarketDataNotFound  %+v", 404, o.Payload)
}

func (o *MarketDataUnsubscribeMarketDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error404NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
