// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CandleResponseDefinitionCandlesItems candle response definition candles items
// swagger:model candleResponseDefinitionCandlesItems
type CandleResponseDefinitionCandlesItems struct {

	// Format of candles [timestamp (epoch), BidOpen, BidClose, BidHigh, BidLow, AskOpen, AskClose, AskHigh, AskLow, TickQty]
	Candle string `json:"candle,omitempty"`
}

// Validate validates this candle response definition candles items
func (m *CandleResponseDefinitionCandlesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CandleResponseDefinitionCandlesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CandleResponseDefinitionCandlesItems) UnmarshalBinary(b []byte) error {
	var res CandleResponseDefinitionCandlesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
