// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CandleResponseDefinitionResponse candle response definition response
// swagger:model candleResponseDefinitionResponse
type CandleResponseDefinitionResponse struct {

	// Type of socket
	Error string `json:"error,omitempty"`

	// Execution successful
	Executed bool `json:"executed,omitempty"`
}

// Validate validates this candle response definition response
func (m *CandleResponseDefinitionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CandleResponseDefinitionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CandleResponseDefinitionResponse) UnmarshalBinary(b []byte) error {
	var res CandleResponseDefinitionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
