// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ChangeOrderRequestDefinition This command will change an existing order that has not been executed.
// swagger:model ChangeOrderRequestDefinition
type ChangeOrderRequestDefinition interface{}
