// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ChangeOrderStopLimitRequestDefinition This command will request the change of a stop loss or limit profit order attached to an entry order.
// swagger:model ChangeOrderStopLimitRequestDefinition
type ChangeOrderStopLimitRequestDefinition interface{}
