// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ChangeTradeStopLimitRequestDefinition This command will request the change of a stop loss or limit profit order attached to a trade.
// swagger:model ChangeTradeStopLimitRequestDefinition
type ChangeTradeStopLimitRequestDefinition interface{}
