// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CloseForAllSymbolsRequestDefinition This command will request the closure of all positions for a specified security.
// swagger:model CloseForAllSymbolsRequestDefinition
type CloseForAllSymbolsRequestDefinition interface{}
