// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClosedPositionResponseDefinition closed position response definition
// swagger:model ClosedPositionResponseDefinition
type ClosedPositionResponseDefinition struct {

	// cloesed position
	CloesedPosition ClosedPositionResponseDefinitionCloesedPosition `json:"cloesedPosition"`
}

// Validate validates this closed position response definition
func (m *ClosedPositionResponseDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ClosedPositionResponseDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClosedPositionResponseDefinition) UnmarshalBinary(b []byte) error {
	var res ClosedPositionResponseDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
