// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// EditOCORequestDefinition This command will request the addition or removal of an existing orders to/from an OCO group.
// swagger:model EditOCORequestDefinition
type EditOCORequestDefinition interface{}
