// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// EntryOrderRequestDefinition This command will request the creation of a standing order to be filled when market reaches the requested price.
// swagger:model EntryOrderRequestDefinition
type EntryOrderRequestDefinition interface{}
