// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Error403Forbidden Forbidden
// swagger:model Error403_Forbidden
type Error403Forbidden struct {

	// code
	Code int32 `json:"Code,omitempty"`

	// The number of API requests per session has been exceeded.
	Message string `json:"Message,omitempty"`
}

// Validate validates this error403 forbidden
func (m *Error403Forbidden) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Error403Forbidden) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Error403Forbidden) UnmarshalBinary(b []byte) error {
	var res Error403Forbidden
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
