// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// HistoricalDataRequestDefinition This command will request historical price data.
// swagger:model HistoricalDataRequestDefinition
type HistoricalDataRequestDefinition interface{}
