// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OfferTableResponseDefinition offer table response definition
// swagger:model OfferTableResponseDefinition
type OfferTableResponseDefinition struct {

	// offers
	Offers OfferTableResponseDefinitionOffers `json:"offers"`
}

// Validate validates this offer table response definition
func (m *OfferTableResponseDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OfferTableResponseDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OfferTableResponseDefinition) UnmarshalBinary(b []byte) error {
	var res OfferTableResponseDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
