// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// OpenTradeRequestDefinition This command will request immediate opening of a trade at the best available price.
// swagger:model OpenTradeRequestDefinition
type OpenTradeRequestDefinition interface{}
