// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OrdersTableResponseDefinition orders table response definition
// swagger:model OrdersTableResponseDefinition
type OrdersTableResponseDefinition struct {

	// orders
	Orders OrdersTableResponseDefinitionOrders `json:"orders"`
}

// Validate validates this orders table response definition
func (m *OrdersTableResponseDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OrdersTableResponseDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrdersTableResponseDefinition) UnmarshalBinary(b []byte) error {
	var res OrdersTableResponseDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
