// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SimpleOCORequestDefinition This command will request the creation of a pair of orders. Execution of one of the orders will cancel the other one.
// swagger:model SimpleOCORequestDefinition
type SimpleOCORequestDefinition interface{}
