// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SubscribeMarketDataRequestDefinition subscribe market data request definition
// swagger:model SubscribeMarketDataRequestDefinition
type SubscribeMarketDataRequestDefinition struct {

	// Symbols to be subscribed to
	Pairs string `json:"pairs,omitempty"`
}

// Validate validates this subscribe market data request definition
func (m *SubscribeMarketDataRequestDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SubscribeMarketDataRequestDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscribeMarketDataRequestDefinition) UnmarshalBinary(b []byte) error {
	var res SubscribeMarketDataRequestDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
