// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UnsubscribeMarketDataResponseDefinition unsubscribe market data response definition
// swagger:model UnsubscribeMarketDataResponseDefinition
type UnsubscribeMarketDataResponseDefinition struct {

	// pairs
	Pairs *UnsubscribeMarketDataResponseDefinitionPairs `json:"pairs,omitempty"`

	// response
	Response *UnsubscribeMarketDataResponseDefinitionResponse `json:"response,omitempty"`
}

// Validate validates this unsubscribe market data response definition
func (m *UnsubscribeMarketDataResponseDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePairs(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateResponse(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnsubscribeMarketDataResponseDefinition) validatePairs(formats strfmt.Registry) error {

	if swag.IsZero(m.Pairs) { // not required
		return nil
	}

	if m.Pairs != nil {

		if err := m.Pairs.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pairs")
			}
			return err
		}
	}

	return nil
}

func (m *UnsubscribeMarketDataResponseDefinition) validateResponse(formats strfmt.Registry) error {

	if swag.IsZero(m.Response) { // not required
		return nil
	}

	if m.Response != nil {

		if err := m.Response.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("response")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnsubscribeMarketDataResponseDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnsubscribeMarketDataResponseDefinition) UnmarshalBinary(b []byte) error {
	var res UnsubscribeMarketDataResponseDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
