// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UnsubscribeMarketDataResponseDefinitionPairs unsubscribe market data response definition pairs
// swagger:model unsubscribeMarketDataResponseDefinitionPairs
type UnsubscribeMarketDataResponseDefinitionPairs struct {

	// Symbols
	Symbol string `json:"Symbol,omitempty"`
}

// Validate validates this unsubscribe market data response definition pairs
func (m *UnsubscribeMarketDataResponseDefinitionPairs) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *UnsubscribeMarketDataResponseDefinitionPairs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnsubscribeMarketDataResponseDefinitionPairs) UnmarshalBinary(b []byte) error {
	var res UnsubscribeMarketDataResponseDefinitionPairs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
