// Code generated by go-swagger; DO NOT EDIT.

package trading_tables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/models"
)

// NewTradingTableOfferTableParams creates a new TradingTableOfferTableParams object
// with the default values initialized.
func NewTradingTableOfferTableParams() *TradingTableOfferTableParams {
	var ()
	return &TradingTableOfferTableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTradingTableOfferTableParamsWithTimeout creates a new TradingTableOfferTableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTradingTableOfferTableParamsWithTimeout(timeout time.Duration) *TradingTableOfferTableParams {
	var ()
	return &TradingTableOfferTableParams{

		timeout: timeout,
	}
}

// NewTradingTableOfferTableParamsWithContext creates a new TradingTableOfferTableParams object
// with the default values initialized, and the ability to set a context for a request
func NewTradingTableOfferTableParamsWithContext(ctx context.Context) *TradingTableOfferTableParams {
	var ()
	return &TradingTableOfferTableParams{

		Context: ctx,
	}
}

// NewTradingTableOfferTableParamsWithHTTPClient creates a new TradingTableOfferTableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTradingTableOfferTableParamsWithHTTPClient(client *http.Client) *TradingTableOfferTableParams {
	var ()
	return &TradingTableOfferTableParams{
		HTTPClient: client,
	}
}

/*TradingTableOfferTableParams contains all the parameters to send to the API endpoint
for the trading table offer table operation typically these are written to a http.Request
*/
type TradingTableOfferTableParams struct {

	/*Body*/
	Body *models.GetTradingTablesSnapshotDefinition

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the trading table offer table params
func (o *TradingTableOfferTableParams) WithTimeout(timeout time.Duration) *TradingTableOfferTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the trading table offer table params
func (o *TradingTableOfferTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the trading table offer table params
func (o *TradingTableOfferTableParams) WithContext(ctx context.Context) *TradingTableOfferTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the trading table offer table params
func (o *TradingTableOfferTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the trading table offer table params
func (o *TradingTableOfferTableParams) WithHTTPClient(client *http.Client) *TradingTableOfferTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the trading table offer table params
func (o *TradingTableOfferTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the trading table offer table params
func (o *TradingTableOfferTableParams) WithBody(body *models.GetTradingTablesSnapshotDefinition) *TradingTableOfferTableParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the trading table offer table params
func (o *TradingTableOfferTableParams) SetBody(body *models.GetTradingTablesSnapshotDefinition) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TradingTableOfferTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
