// Code generated by go-swagger; DO NOT EDIT.

package trading_tables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/models"
)

// NewTradingTableClosedPositionsParams creates a new TradingTableClosedPositionsParams object
// with the default values initialized.
func NewTradingTableClosedPositionsParams() *TradingTableClosedPositionsParams {
	var ()
	return &TradingTableClosedPositionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTradingTableClosedPositionsParamsWithTimeout creates a new TradingTableClosedPositionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTradingTableClosedPositionsParamsWithTimeout(timeout time.Duration) *TradingTableClosedPositionsParams {
	var ()
	return &TradingTableClosedPositionsParams{

		timeout: timeout,
	}
}

// NewTradingTableClosedPositionsParamsWithContext creates a new TradingTableClosedPositionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewTradingTableClosedPositionsParamsWithContext(ctx context.Context) *TradingTableClosedPositionsParams {
	var ()
	return &TradingTableClosedPositionsParams{

		Context: ctx,
	}
}

// NewTradingTableClosedPositionsParamsWithHTTPClient creates a new TradingTableClosedPositionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTradingTableClosedPositionsParamsWithHTTPClient(client *http.Client) *TradingTableClosedPositionsParams {
	var ()
	return &TradingTableClosedPositionsParams{
		HTTPClient: client,
	}
}

/*TradingTableClosedPositionsParams contains all the parameters to send to the API endpoint
for the trading table closed positions operation typically these are written to a http.Request
*/
type TradingTableClosedPositionsParams struct {

	/*Body*/
	Body *models.GetTradingTablesSnapshotDefinition

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) WithTimeout(timeout time.Duration) *TradingTableClosedPositionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) WithContext(ctx context.Context) *TradingTableClosedPositionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) WithHTTPClient(client *http.Client) *TradingTableClosedPositionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) WithBody(body *models.GetTradingTablesSnapshotDefinition) *TradingTableClosedPositionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the trading table closed positions params
func (o *TradingTableClosedPositionsParams) SetBody(body *models.GetTradingTablesSnapshotDefinition) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TradingTableClosedPositionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
