// Code generated by go-swagger; DO NOT EDIT.

package trading_tables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/models"
)

// NewTradingTableOrdersTableParams creates a new TradingTableOrdersTableParams object
// with the default values initialized.
func NewTradingTableOrdersTableParams() *TradingTableOrdersTableParams {
	var ()
	return &TradingTableOrdersTableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTradingTableOrdersTableParamsWithTimeout creates a new TradingTableOrdersTableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTradingTableOrdersTableParamsWithTimeout(timeout time.Duration) *TradingTableOrdersTableParams {
	var ()
	return &TradingTableOrdersTableParams{

		timeout: timeout,
	}
}

// NewTradingTableOrdersTableParamsWithContext creates a new TradingTableOrdersTableParams object
// with the default values initialized, and the ability to set a context for a request
func NewTradingTableOrdersTableParamsWithContext(ctx context.Context) *TradingTableOrdersTableParams {
	var ()
	return &TradingTableOrdersTableParams{

		Context: ctx,
	}
}

// NewTradingTableOrdersTableParamsWithHTTPClient creates a new TradingTableOrdersTableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTradingTableOrdersTableParamsWithHTTPClient(client *http.Client) *TradingTableOrdersTableParams {
	var ()
	return &TradingTableOrdersTableParams{
		HTTPClient: client,
	}
}

/*TradingTableOrdersTableParams contains all the parameters to send to the API endpoint
for the trading table orders table operation typically these are written to a http.Request
*/
type TradingTableOrdersTableParams struct {

	/*Body*/
	Body *models.GetTradingTablesSnapshotDefinition

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the trading table orders table params
func (o *TradingTableOrdersTableParams) WithTimeout(timeout time.Duration) *TradingTableOrdersTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the trading table orders table params
func (o *TradingTableOrdersTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the trading table orders table params
func (o *TradingTableOrdersTableParams) WithContext(ctx context.Context) *TradingTableOrdersTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the trading table orders table params
func (o *TradingTableOrdersTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the trading table orders table params
func (o *TradingTableOrdersTableParams) WithHTTPClient(client *http.Client) *TradingTableOrdersTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the trading table orders table params
func (o *TradingTableOrdersTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the trading table orders table params
func (o *TradingTableOrdersTableParams) WithBody(body *models.GetTradingTablesSnapshotDefinition) *TradingTableOrdersTableParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the trading table orders table params
func (o *TradingTableOrdersTableParams) SetBody(body *models.GetTradingTablesSnapshotDefinition) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TradingTableOrdersTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
