// Code generated by go-swagger; DO NOT EDIT.

package trading_tables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nii236/fxcm-go/models"
)

// NewTradingTableSnapshotParams creates a new TradingTableSnapshotParams object
// with the default values initialized.
func NewTradingTableSnapshotParams() *TradingTableSnapshotParams {
	var ()
	return &TradingTableSnapshotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTradingTableSnapshotParamsWithTimeout creates a new TradingTableSnapshotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTradingTableSnapshotParamsWithTimeout(timeout time.Duration) *TradingTableSnapshotParams {
	var ()
	return &TradingTableSnapshotParams{

		timeout: timeout,
	}
}

// NewTradingTableSnapshotParamsWithContext creates a new TradingTableSnapshotParams object
// with the default values initialized, and the ability to set a context for a request
func NewTradingTableSnapshotParamsWithContext(ctx context.Context) *TradingTableSnapshotParams {
	var ()
	return &TradingTableSnapshotParams{

		Context: ctx,
	}
}

// NewTradingTableSnapshotParamsWithHTTPClient creates a new TradingTableSnapshotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTradingTableSnapshotParamsWithHTTPClient(client *http.Client) *TradingTableSnapshotParams {
	var ()
	return &TradingTableSnapshotParams{
		HTTPClient: client,
	}
}

/*TradingTableSnapshotParams contains all the parameters to send to the API endpoint
for the trading table snapshot operation typically these are written to a http.Request
*/
type TradingTableSnapshotParams struct {

	/*Body*/
	Body *models.GetTradingTablesSnapshotDefinition

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the trading table snapshot params
func (o *TradingTableSnapshotParams) WithTimeout(timeout time.Duration) *TradingTableSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the trading table snapshot params
func (o *TradingTableSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the trading table snapshot params
func (o *TradingTableSnapshotParams) WithContext(ctx context.Context) *TradingTableSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the trading table snapshot params
func (o *TradingTableSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the trading table snapshot params
func (o *TradingTableSnapshotParams) WithHTTPClient(client *http.Client) *TradingTableSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the trading table snapshot params
func (o *TradingTableSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the trading table snapshot params
func (o *TradingTableSnapshotParams) WithBody(body *models.GetTradingTablesSnapshotDefinition) *TradingTableSnapshotParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the trading table snapshot params
func (o *TradingTableSnapshotParams) SetBody(body *models.GetTradingTablesSnapshotDefinition) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TradingTableSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
